Events:

  # Gloal Event settings
  Global:
    # Amount in seconds between every chance of a random event
    EventRepeatDelay: 300

    # Amount in percentage (out of 100%) that an event will happen
    EventChance: 5

    # List of world names that can have events happening in them.
    Worlds: [world]

  # Earthquake Specific settings
  Earthquake:
    # This turns on and off the earthquake event. (true = on, false = off)
    Enabled: true

    # This turns on and off the earthquake broadcast. (true = on, false = off)
    Broadcast: true

    # This specifices the location where the earthquake will be dropped. More info below.
    LocationType: NEAR_SPAWN

  # Meteorite Specific settings
  Meteorite:
    # This turns on and off the meteorite event. (true = on, false = off)
    Enabled: true

    # This turns on and off the meteorite broadcast. (true = on, false = off)
    Broadcast: true

    # This specifices the location where the meteorite will be dropped. More info below.
    LocationType: NEAR_SPAWN

  # Hailstorm Specific settings
  Hailstorm:
    # This turns on and off the hailstorm event. (true = on, false = off)
    Enabled: true

    # This turns on and off the hailstorm broadcast. (true = on, false = off)
    Broadcast: true

    # This specifices the location where the hailstorm will be dropped. More info below.
    LocationType: NEAR_SPAWN

  # GRB Specific settings
  GRB:
    # This turns on and off the GRB event. (true = on, false = off)
    Enabled: true

    # This turns on and off the GRB broadcast. (true = on, false = off)
    Broadcast: true

    # This specifices the location where the GRB will be dropped. More info below.
    LocationType: NEAR_SPAWN


# Where you are able to specify a location, these are the valid options and their descriptions.
# Available Options: 
# RANDOM: Will spawn at a completely random location between -100 000 and +100 000.
# PLAYER: Will choose a random player and spawn near that player.
# NEAR_SPAWN: Will spawn at a location that is near the spawn.
# LOADED_CHUNK:  Will spawn in a loaded chunk.